#!/bin/sh

if [ 0 -eq $# ]; then
    id=`cat ./current_id`
else
    id=$1
fi

if [ ! -e problems/$id ];then
    echo "problem ID [$id] not exist"
    exit 1
fi

cat problems/$id/title
echo 
cat problems/$id/desc

